# Generated by Django 5.1.2 on 2024-11-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiveisDeRuido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('hora', models.CharField(max_length=8)),
                ('decibeis', models.FloatField()),
                ('limite', models.FloatField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
