# Generated by Django 5.1.2 on 2024-11-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInterface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='niveisderuido',
            table='userinterfaceniveisderuido',
        ),
    ]
