# Generated by Django 5.1.2 on 2024-11-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInterface', '0002_alter_niveisderuido_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='niveisderuido',
            table=None,
        ),
    ]
