# Generated by Django 5.1.2 on 2024-11-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInterface', '0003_alter_niveisderuido_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveisderuido',
            name='data',
            field=models.DateField(),
        ),
    ]
