# Generated by Django 5.1.2 on 2024-11-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInterface', '0004_alter_niveisderuido_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='bancodosom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.CharField(max_length=8)),
                ('decibeis', models.FloatField()),
                ('limite', models.FloatField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
