# Generated by Django 5.1.2 on 2024-11-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInterface', '0005_bancodosom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bancodosom',
        ),
    ]
