# Generated by Django 5.1.2 on 2024-11-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInterface', '0006_delete_bancodosom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveisderuido',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='niveisderuido',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AddIndex(
            model_name='niveisderuido',
            index=models.Index(fields=['data', 'hora'], name='userInterfa_data_859d94_idx'),
        ),
        migrations.AddIndex(
            model_name='niveisderuido',
            index=models.Index(fields=['status'], name='userInterfa_status_8e03b9_idx'),
        ),
    ]
